# Fake change
image:
  repository: ghcr.io/linuxserver/cloud9
  pullPolicy: IfNotPresent
  tag: version-1.29.2@sha256:9406e20f2c8c8c0372990e4d1147529de55b499a61c323ea2f96c76b59d77cfd

# USERNAME="" #optional
# PASSWORD="" #optional

env:
  PUID: 568

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8000

persistence:
  code:
    enabled: true
    mountPath: /code
    accessMode: ReadWriteOnce
    size: 1Gi
  sock:
    enabled: true
    mountPath: /var/run/docker.sock
    accessMode: ReadWriteOnce
    size: 1Gi
  varrun:
    enabled: true
